# Generated by Django 3.2.14 on 2024-08-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20240831_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/')),
                ('description', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='allproducts',
            name='image',
        ),
        migrations.AddField(
            model_name='allproducts',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.Image'),
        ),
    ]
