# Generated by Django 3.2.14 on 2024-09-02 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20240831_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pods',
            fields=[
                ('allproducts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.allproducts')),
                ('colour', models.CharField(blank=True, max_length=254, null=True)),
                ('built_in_battery', models.BooleanField(default=False)),
                ('battery_size', models.CharField(blank=True, max_length=254, null=True)),
                ('output', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pods',
            },
            bases=('products.allproducts',),
        ),
    ]
