# Generated by Django 3.2.14 on 2024-09-12 07:40

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_pods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproducts',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
