# Generated by Django 3.2.14 on 2024-09-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_allproducts_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproducts',
            name='description',
            field=models.TextField(),
        ),
    ]
